### ISSUE TITLE
Cannot read property 'provide' of undefined

### ISSUE THREAD

**Issue by 1459416736** [notadd/next#3]
**next版本:**2.4.2

执行yarn run dev 的时候报错
**What happened instead:**

`TypeError: Cannot read property 'provide' of undefined
    at Module.isCustomProvider (/srv/next2/node_modules/@nestjs/core/injector/module.js:135:48)
    at Module.addComponent (/srv/next2/node_modules/@nestjs/core/injector/module.js:123:18)
    at NestContainer.addComponent (/srv/next2/node_modules/@nestjs/core/injector/container.js:79:23)
    at DependenciesScanner.storeComponent (/srv/next2/node_modules/@nestjs/core/scanner.js:129:35)
    at components.map.component (/srv/next2/node_modules/@nestjs/core/scanner.js:58:18)
    at Array.map (<anonymous>)
    at DependenciesScanner.reflectComponents (/srv/next2/node_modules/@nestjs/core/scanner.js:57:20)
    at modules.forEach (/srv/next2/node_modules/@nestjs/core/scanner.js:38:18)
    at Map.forEach (<anonymous>)
    at DependenciesScanner.scanModulesForDependencies (/srv/next2/node_modules/@nestjs/core/scanner.js:36:17)
 1: node::Abort() [/usr/local/bin/node]
 2: 0x55617f686bd9 [/usr/local/bin/node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 4: 0x55617ef4101f [/usr/local/bin/node]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x23751d2042fd`

**Comment by twilroad** [comment]
问题分析中……

**Comment by twilroad** [comment]
使用注解的export的顺序问题导致，已修复
